### Spring
spring:
  profiles:
    active: "local"

  security.basic.enabled: false

### Logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
  file.max-size: 100MB
  file.max-history: 10
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    file: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
