### DB
  datasource:
    url: jdbc:postgresql://localhost:15432/silcom-sms
    username: silcom-sms
    password: silcom-sms

  jpa:
    hibernate:
      ddl-auto: create-drop

### Logging
logging:
  file: ./log/silcom-sms/local.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

    # SQL LOG
    org.hibernate.SQL: DEBUG

### Server
server:
  port: 7777
